Simplify: use domain name as zone name in all cases
I don't understand what caused the error before (see below) but:
- creating a zone named "jacquev6.net" was impossible
- so I used "jacquev6.net-2"
- and discovered that I could rename it to "jacquev6.net" later

Error from `terraform apply`:

    Error: Error applying plan:
    1 error(s) occurred:
    * module.splight_fr.gandi_zone.zone: 1 error(s) occurred:
    * gandi_zone.zone: 409: Zone splight.fr already exists